language:
  python

python: 3.7
dist: xenial
sudo: true

install:
  pip3 install torch torchvision
  pip install numpy
  pip install torch


script:
  PWD = 'pwd'
  export PYTHONPATH="$PYTHONPATH:$PWD"
  pytest Tests/*.py








