language:
  python

python: 3.7
dist: xenial
sudo: true

install:
  - pip install numpy -q
  - pip install torch -q
  - pip install gym -q


script:
  - export PYTHONPATH="$PYTHONPATH:$PWD"
  - pytest Tests/*.py











