language:
  python

python: 3.7
dist: xenial
sudo: true

install:
  - pip install -r requirements.txt


script:
  - export PYTHONPATH="$PYTHONPATH:$PWD"
  - export PYTHONPATH=""$PYTHONPATH:$PWD/Agents""
  - export PYTHONPATH=""$PYTHONPATH:$PWD/Environments""
  - pytest Tests/*.py











